<Project Sdk="Microsoft.NET.Sdk">

  <!-- Standard C# project properties -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- Publish properties (in case someone would like to do that for some reason) -->
  <PropertyGroup>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <!-- Nuget properties -->
  <PropertyGroup>
    <PackageId>ferafiks.Stride.Cli</PackageId>
    <Version>1.0.1</Version>
    <Authors>ferafiks</Authors>
    <Description>A command-line program for managing Stride 3D projects without the need for Game Studio.</Description>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>stride-frfks</ToolCommandName>
    <PackageTags>stride;gamedev;cli;dotnet-tool</PackageTags>
    <AssemblyName>stride-frfks</AssemblyName>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/ferafiks/ferafiks.Stride.Cli</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- Packages -->
  <ItemGroup>
    <PackageReference Include="Stride.Assets" Version="4.4.0-beta5" />
    <PackageReference Include="Stride.Assets.Models" Version="4.4.0-beta5" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />

    <PackageReference Include="Microsoft.Build.Framework" Version="18.3.3" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>

  <!-- Nuget item includes -->
  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="/"/>
    <None Include="../README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>

</Project>
